// Package catalog validates and normalizes catalog bundles.
package catalog

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/SomethingCreativeStudios/tlon/internal/cql"
	"github.com/SomethingCreativeStudios/tlon/internal/recordschema"
	"github.com/SomethingCreativeStudios/tlon/store"
)

var namePattern = regexp.MustCompile(`^[A-Za-z0-9_.:-]+$`)
var isoIntervalPattern = regexp.MustCompile(`^P(?:(?:[0-9]+(?:\.[0-9]+)?D)?(?:T(?:[0-9]+(?:\.[0-9]+)?H)?(?:[0-9]+(?:\.[0-9]+)?M)?(?:[0-9]+(?:\.[0-9]+)?S)?)?)$`)

const (
	maximumCatalogIndexes = 16
	maximumIndexKeys      = 4
)

func Normalize(bundle store.CatalogBundle) (store.CatalogBundle, string, error) {
	var doc map[string]any
	if len(bundle.Catalog) == 0 || json.Unmarshal(bundle.Catalog, &doc) != nil {
		return bundle, "", fmt.Errorf("catalog must be a JSON object")
	}
	id, ok := doc["id"].(string)
	if !ok || strings.TrimSpace(id) == "" {
		return bundle, "", fmt.Errorf("catalog.id is required")
	}
	if doc["type"] != "Collection" {
		return bundle, "", fmt.Errorf("catalog.type must be Collection")
	}
	if doc["itemType"] != "record" {
		return bundle, "", fmt.Errorf("catalog.itemType must be record")
	}
	doc["supportsNonAutogeneratedResourceIds"] = true
	delete(doc, "links")
	if bundle.Storage.Class == "" {
		bundle.Storage.Class = store.StorageTransactional
	}
	switch bundle.Storage.Class {
	case store.StorageTransactional, store.StorageTemporal:
	default:
		return bundle, "", fmt.Errorf("storage.class must be %q or %q", store.StorageTransactional, store.StorageTemporal)
	}
	if bundle.Storage.AutoFacetIndexes == nil {
		automatic := true
		bundle.Storage.AutoFacetIndexes = &automatic
	}
	if bundle.Queryables == nil {
		bundle.Queryables = map[string]store.Queryable{}
	}
	defaults := map[string]store.Queryable{
		"id":          {Title: "Record identifier", Type: "string", Path: "/id"},
		"type":        {Title: "Record type", Type: "string", Path: "/properties/type"},
		"title":       {Title: "Title", Type: "string", Path: "/properties/title"},
		"description": {Title: "Description", Type: "string", Path: "/properties/description"},
		"created":     {Title: "Created", Type: "string", Format: "date-time", Path: "/properties/created"},
		"updated":     {Title: "Updated", Type: "string", Format: "date-time", Path: "/properties/updated"},
	}
	for name, q := range defaults {
		if _, exists := bundle.Queryables[name]; !exists {
			bundle.Queryables[name] = q
		}
	}
	for name, q := range bundle.Queryables {
		if !namePattern.MatchString(name) {
			return bundle, "", fmt.Errorf("invalid queryable name %q", name)
		}
		if _, err := cql.PropertySQL(name, q); err != nil {
			return bundle, "", fmt.Errorf("queryable %q: %w", name, err)
		}
	}
	if len(bundle.Storage.Indexes) > maximumCatalogIndexes {
		return bundle, "", fmt.Errorf("storage.indexes supports at most %d indexes", maximumCatalogIndexes)
	}
	indexNames := make(map[string]struct{}, len(bundle.Storage.Indexes))
	indexDefinitions := make(map[string]struct{}, len(bundle.Storage.Indexes))
	for index := range bundle.Storage.Indexes {
		definition := &bundle.Storage.Indexes[index]
		if !namePattern.MatchString(definition.Name) {
			return bundle, "", fmt.Errorf("invalid storage index name %q", definition.Name)
		}
		if _, exists := indexNames[definition.Name]; exists {
			return bundle, "", fmt.Errorf("duplicate storage index name %q", definition.Name)
		}
		indexNames[definition.Name] = struct{}{}
		if len(definition.Keys) == 0 || len(definition.Keys) > maximumIndexKeys {
			return bundle, "", fmt.Errorf("storage index %q must have between one and %d keys", definition.Name, maximumIndexKeys)
		}
		properties := make(map[string]struct{}, len(definition.Keys))
		parts := make([]string, len(definition.Keys))
		for keyIndex := range definition.Keys {
			key := &definition.Keys[keyIndex]
			queryable, exists := bundle.Queryables[key.Property]
			if !exists {
				return bundle, "", fmt.Errorf("storage index %q uses unknown queryable %q", definition.Name, key.Property)
			}
			if queryable.Type == "array" || queryable.Items != nil {
				return bundle, "", fmt.Errorf("storage index %q cannot use array queryable %q", definition.Name, key.Property)
			}
			if _, exists := properties[key.Property]; exists {
				return bundle, "", fmt.Errorf("storage index %q repeats queryable %q", definition.Name, key.Property)
			}
			properties[key.Property] = struct{}{}
			key.Direction = strings.ToLower(key.Direction)
			if key.Direction == "" {
				key.Direction = "asc"
			}
			if key.Direction != "asc" && key.Direction != "desc" {
				return bundle, "", fmt.Errorf("storage index %q has invalid direction for %q", definition.Name, key.Property)
			}
			parts[keyIndex] = key.Property + ":" + key.Direction
		}
		signature := strings.Join(parts, ",")
		if _, exists := indexDefinitions[signature]; exists {
			return bundle, "", fmt.Errorf("storage index %q duplicates another index definition", definition.Name)
		}
		indexDefinitions[signature] = struct{}{}
	}
	if bundle.Sortables == nil {
		bundle.Sortables = map[string]store.Sortable{}
	}
	for _, name := range []string{"id", "created", "updated", "title", "type"} {
		if _, exists := bundle.Sortables[name]; !exists {
			q := bundle.Queryables[name]
			bundle.Sortables[name] = store.Sortable{Title: q.Title, Type: q.Type, Format: q.Format, Path: q.Path}
		}
	}
	for name, sortable := range bundle.Sortables {
		if !namePattern.MatchString(name) {
			return bundle, "", fmt.Errorf("invalid sortable name %q", name)
		}
		q := store.Queryable{Type: sortable.Type, Format: sortable.Format, Path: sortable.Path}
		if _, err := cql.PropertySQL(name, q); err != nil {
			return bundle, "", fmt.Errorf("sortable %q: %w", name, err)
		}
	}
	if len(bundle.DefaultSortOrder) == 0 {
		bundle.DefaultSortOrder = []store.SortField{{Property: "updated", Direction: "desc"}}
	}
	for i := range bundle.DefaultSortOrder {
		field := &bundle.DefaultSortOrder[i]
		field.Direction = strings.ToLower(field.Direction)
		if field.Direction == "" {
			field.Direction = "asc"
		}
		if field.Direction != "asc" && field.Direction != "desc" {
			return bundle, "", fmt.Errorf("invalid sort direction for %q", field.Property)
		}
		if _, ok := bundle.Sortables[field.Property]; !ok {
			return bundle, "", fmt.Errorf("default sort property %q is not sortable", field.Property)
		}
	}
	for name, facet := range bundle.Facets {
		if !namePattern.MatchString(name) {
			return bundle, "", fmt.Errorf("invalid facet name %q", name)
		}
		if facet.BucketCount < 0 || facet.MinOccurs < 0 {
			return bundle, "", fmt.Errorf("facet %q has negative limits", name)
		}
		if facet.BucketCount == 0 {
			facet.BucketCount = 10
		}
		if facet.SortedBy == "" {
			facet.SortedBy = "count"
		}
		switch facet.Type {
		case store.FacetTerm:
			if _, ok := bundle.Queryables[facet.Property]; !ok {
				return bundle, "", fmt.Errorf("facet %q uses unknown property %q", name, facet.Property)
			}
		case store.FacetHistogram:
			q, ok := bundle.Queryables[facet.Property]
			if !ok {
				return bundle, "", fmt.Errorf("facet %q uses unknown property %q", name, facet.Property)
			}
			if q.Type != "number" && q.Type != "integer" && q.Format != "date-time" {
				return bundle, "", fmt.Errorf("histogram facet %q requires numeric or date-time property", name)
			}
			if facet.BucketType == "" {
				facet.BucketType = store.BucketFixedCount
			}
			switch facet.BucketType {
			case store.BucketFixedCount:
			case store.BucketFixedInterval:
				if err := validateInterval(facet.Interval, q.Format == "date-time"); err != nil {
					return bundle, "", fmt.Errorf("facet %q: %w", name, err)
				}
			default:
				return bundle, "", fmt.Errorf("facet %q has invalid bucketType", name)
			}
		case store.FacetFilter:
			if len(facet.Filters) == 0 {
				return bundle, "", fmt.Errorf("filter facet %q requires filters", name)
			}
			for bucket, filter := range facet.Filters {
				if strings.TrimSpace(bucket) == "" {
					return bundle, "", fmt.Errorf("filter facet %q has an empty bucket name", name)
				}
				if err := cql.Validate(filter, bundle.Queryables); err != nil {
					return bundle, "", fmt.Errorf("filter facet %q bucket %q: %w", name, bucket, err)
				}
			}
		default:
			return bundle, "", fmt.Errorf("facet %q has invalid type %q", name, facet.Type)
		}
		bundle.Facets[name] = facet
	}
	bundle.Catalog, _ = json.Marshal(doc)
	if len(bundle.Schema) == 0 {
		bundle.Schema = defaultSchema()
	}
	if _, err := recordschema.Compile(bundle.Schema); err != nil {
		return bundle, "", fmt.Errorf("schema: %w", err)
	}
	return bundle, id, nil
}

// NormalizeSort validates client ordering and appends the deterministic id
// tie-breaker used by both cursor signing and storage.
func NormalizeSort(requested, defaults []store.SortField, allowed map[string]store.Sortable) ([]store.SortField, error) {
	fields := append([]store.SortField(nil), requested...)
	if len(fields) == 0 {
		fields = append(fields, defaults...)
	}
	if len(fields) == 0 {
		fields = []store.SortField{{Property: "id", Direction: "asc"}}
	}
	if len(fields) > 8 {
		return nil, fmt.Errorf("at most eight sort fields are supported")
	}
	hasID := false
	for i := range fields {
		fields[i].Direction = strings.ToLower(fields[i].Direction)
		if fields[i].Direction == "" {
			fields[i].Direction = "asc"
		}
		if fields[i].Direction != "asc" && fields[i].Direction != "desc" {
			return nil, fmt.Errorf("invalid sort direction for %q", fields[i].Property)
		}
		if _, ok := allowed[fields[i].Property]; !ok {
			return nil, fmt.Errorf("property %q is not sortable", fields[i].Property)
		}
		if fields[i].Property == "id" {
			hasID = true
		}
	}
	if !hasID {
		fields = append(fields, store.SortField{Property: "id", Direction: "asc"})
	}
	return fields, nil
}

func validateInterval(raw json.RawMessage, temporal bool) error {
	if len(raw) == 0 {
		return fmt.Errorf("fixedInterval requires interval")
	}
	if temporal {
		var value string
		if json.Unmarshal(raw, &value) != nil || !isoIntervalPattern.MatchString(value) || value == "P" || value == "PT" {
			return fmt.Errorf("interval must be an ISO-8601 day/time duration")
		}
		return nil
	}
	var value float64
	if json.Unmarshal(raw, &value) != nil || value <= 0 {
		return fmt.Errorf("interval must be a positive number")
	}
	return nil
}

func defaultSchema() json.RawMessage {
	return json.RawMessage(`{"$schema":"https://json-schema.org/draft/2020-12/schema","title":"OGC Record","type":"object","required":["type","geometry","properties"],"properties":{"id":{"type":"string","readOnly":true},"type":{"const":"Feature"},"geometry":{"type":["object","null"]},"properties":{"type":"object","required":["type"],"properties":{"type":{"type":"string"},"created":{"type":"string","format":"date-time","readOnly":true},"updated":{"type":"string","format":"date-time","readOnly":true}},"additionalProperties":true}},"additionalProperties":true}`)
}
