package catalog

import (
	"encoding/json"
	"testing"

	"github.com/SomethingCreativeStudios/tlon/store"
)

func validBundle() store.CatalogBundle {
	return store.CatalogBundle{Catalog: json.RawMessage(`{"id":"records","type":"Collection","itemType":"record"}`), Queryables: map[string]store.Queryable{"score": {Type: "number", Path: "/properties/score"}}, Facets: map[string]store.FacetDefinition{"score": {Type: store.FacetHistogram, Property: "score", BucketType: store.BucketFixedInterval, Interval: json.RawMessage(`5`)}, "kind": {Type: store.FacetFilter, Filters: map[string]string{"high": "score >= 10"}}}}
}
func TestNormalizeBundle(t *testing.T) {
	bundle, id, err := Normalize(validBundle())
	if err != nil {
		t.Fatal(err)
	}
	if id != "records" {
		t.Errorf("id = %s", id)
	}
	if _, ok := bundle.Queryables["updated"]; !ok {
		t.Error("core queryables not added")
	}
	var doc map[string]any
	_ = json.Unmarshal(bundle.Catalog, &doc)
	if doc["supportsNonAutogeneratedResourceIds"] != true {
		t.Error("client IDs not advertised")
	}
	if len(bundle.Schema) == 0 {
		t.Error("default record schema not added")
	}
}
func TestRejectInvalidFacetConfiguration(t *testing.T) {
	bundle := validBundle()
	facet := bundle.Facets["score"]
	facet.Interval = json.RawMessage(`0`)
	bundle.Facets["score"] = facet
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("zero interval accepted")
	}
	bundle = validBundle()
	facet = bundle.Facets["kind"]
	facet.Filters["bad"] = "unknown = 1"
	bundle.Facets["kind"] = facet
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("invalid filter facet accepted")
	}
}

func TestRejectInvalidRecordSchema(t *testing.T) {
	bundle := validBundle()
	bundle.Schema = json.RawMessage(`{"type":7}`)
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("invalid record schema accepted")
	}
}
