package catalog

import (
	"encoding/json"
	"testing"

	"github.com/SomethingCreativeStudios/tlon/store"
)

func validBundle() store.CatalogBundle {
	return store.CatalogBundle{Catalog: json.RawMessage(`{"id":"records","type":"Collection","itemType":"record"}`), Queryables: map[string]store.Queryable{"score": {Type: "number", Path: "/properties/score"}}, Facets: map[string]store.FacetDefinition{"score": {Type: store.FacetHistogram, Property: "score", BucketType: store.BucketFixedInterval, Interval: json.RawMessage(`5`)}, "kind": {Type: store.FacetFilter, Filters: map[string]string{"high": "score >= 10"}}}}
}
func TestNormalizeBundle(t *testing.T) {
	bundle, id, err := Normalize(validBundle())
	if err != nil {
		t.Fatal(err)
	}
	if id != "records" {
		t.Errorf("id = %s", id)
	}
	if _, ok := bundle.Queryables["updated"]; !ok {
		t.Error("core queryables not added")
	}
	var doc map[string]any
	_ = json.Unmarshal(bundle.Catalog, &doc)
	if doc["supportsNonAutogeneratedResourceIds"] != true {
		t.Error("client IDs not advertised")
	}
	if len(bundle.Schema) == 0 {
		t.Error("default record schema not added")
	}
	if bundle.Storage.Class != store.StorageTransactional {
		t.Errorf("default storage class = %q", bundle.Storage.Class)
	}
	if bundle.Storage.AutoFacetIndexes == nil || !*bundle.Storage.AutoFacetIndexes {
		t.Error("automatic facet indexes are not enabled by default")
	}
}

func TestNormalizeStorageIndexes(t *testing.T) {
	bundle := validBundle()
	bundle.Storage.Indexes = []store.CatalogIndex{{
		Name: "score-updated",
		Keys: []store.IndexKey{{Property: "score"}, {Property: "updated", Direction: "DESC"}},
	}}
	normalized, _, err := Normalize(bundle)
	if err != nil {
		t.Fatal(err)
	}
	keys := normalized.Storage.Indexes[0].Keys
	if keys[0].Direction != "asc" || keys[1].Direction != "desc" {
		t.Fatalf("normalized keys = %#v", keys)
	}
}

func TestRejectInvalidStorageIndexes(t *testing.T) {
	tests := []struct {
		name  string
		index store.CatalogIndex
	}{
		{name: "missing name", index: store.CatalogIndex{Keys: []store.IndexKey{{Property: "score"}}}},
		{name: "missing keys", index: store.CatalogIndex{Name: "empty"}},
		{name: "unknown queryable", index: store.CatalogIndex{Name: "unknown", Keys: []store.IndexKey{{Property: "missing"}}}},
		{name: "invalid direction", index: store.CatalogIndex{Name: "direction", Keys: []store.IndexKey{{Property: "score", Direction: "sideways"}}}},
		{name: "repeated property", index: store.CatalogIndex{Name: "repeat", Keys: []store.IndexKey{{Property: "score"}, {Property: "score"}}}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			bundle := validBundle()
			bundle.Storage.Indexes = []store.CatalogIndex{test.index}
			if _, _, err := Normalize(bundle); err == nil {
				t.Fatal("invalid storage index accepted")
			}
		})
	}

	bundle := validBundle()
	bundle.Queryables["keywords"] = store.Queryable{Type: "array", Items: &store.Queryable{Type: "string"}, Path: "/properties/keywords"}
	bundle.Storage.Indexes = []store.CatalogIndex{{Name: "keywords", Keys: []store.IndexKey{{Property: "keywords"}}}}
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("array storage index accepted")
	}
}

func TestNormalizeTemporalStorage(t *testing.T) {
	bundle := validBundle()
	bundle.Storage.Class = store.StorageTemporal
	normalized, _, err := Normalize(bundle)
	if err != nil {
		t.Fatal(err)
	}
	if normalized.Storage.Class != store.StorageTemporal {
		t.Errorf("storage class = %q", normalized.Storage.Class)
	}

	bundle.Storage.Class = "observations"
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("unknown storage class accepted")
	}
}
func TestRejectInvalidFacetConfiguration(t *testing.T) {
	bundle := validBundle()
	facet := bundle.Facets["score"]
	facet.Interval = json.RawMessage(`0`)
	bundle.Facets["score"] = facet
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("zero interval accepted")
	}
	bundle = validBundle()
	facet = bundle.Facets["kind"]
	facet.Filters["bad"] = "unknown = 1"
	bundle.Facets["kind"] = facet
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("invalid filter facet accepted")
	}
}

func TestRejectInvalidRecordSchema(t *testing.T) {
	bundle := validBundle()
	bundle.Schema = json.RawMessage(`{"type":7}`)
	if _, _, err := Normalize(bundle); err == nil {
		t.Fatal("invalid record schema accepted")
	}
}
