package server

import (
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"github.com/SomethingCreativeStudios/tlon/api"
	"github.com/SomethingCreativeStudios/tlon/catalog"
	"github.com/SomethingCreativeStudios/tlon/internal/cursor"
	"github.com/SomethingCreativeStudios/tlon/internal/etag"
	"github.com/SomethingCreativeStudios/tlon/store"
)

const catalogProfile = "http://www.opengis.net/def/profile/OGC/0/ogc-catalog"

func (s *Service) recordModel(stored store.StoredRecord) (api.Record, error) {
	var result api.Record
	err := json.Unmarshal(stored.Document, &result)
	return result, err
}

func (s *Service) catalogModel(value store.Catalog) (api.Catalog, error) {
	var doc map[string]any
	if err := json.Unmarshal(value.Bundle.Catalog, &doc); err != nil {
		return api.Catalog{}, err
	}
	base := s.publicURL + "/collections/" + url.PathEscape(value.ID)
	doc["supportsNonAutogeneratedResourceIds"] = true
	doc["defaultSortOrder"] = value.Bundle.DefaultSortOrder
	doc["conformsTo"] = []string{catalogProfile}
	doc["links"] = []any{
		map[string]any{"rel": "self", "type": "application/json", "href": base}, map[string]any{"rel": "items", "type": "application/geo+json", "href": base + "/items"}, map[string]any{"rel": "queryables", "type": "application/schema+json", "href": base + "/queryables"}, map[string]any{"rel": "sortables", "type": "application/schema+json", "href": base + "/sortables"}, map[string]any{"rel": "facets", "type": "application/facets+json", "href": base + "/facets"}, map[string]any{"rel": "describedby", "type": "application/schema+json", "href": base + "/schema"}, map[string]any{"rel": "profile", "type": "text/html", "href": catalogProfile}}
	raw, err := json.Marshal(doc)
	if err != nil {
		return api.Catalog{}, err
	}
	var result api.Catalog
	err = json.Unmarshal(raw, &result)
	return result, err
}

func parseSort(values *[]string) ([]store.SortField, error) {
	if values == nil {
		return nil, nil
	}
	result := make([]store.SortField, 0, len(*values))
	for _, value := range *values {
		value = strings.TrimSpace(value)
		if value == "" {
			return nil, fmt.Errorf("invalid empty sort field")
		}
		direction := "asc"
		if value[0] == '+' {
			value = value[1:]
		} else if value[0] == '-' {
			direction = "desc"
			value = value[1:]
		}
		if value == "" {
			return nil, fmt.Errorf("invalid empty sort field")
		}
		result = append(result, store.SortField{Property: value, Direction: direction})
	}
	return result, nil
}

func (s *Service) recordSearch(catalogValue store.Catalog, params api.SearchRecordsParams) (store.Search, string, error) {
	search := store.Search{Limit: s.defaultLimit}
	if params.Bbox != nil {
		for _, v := range *params.Bbox {
			search.Bbox = append(search.Bbox, float64(v))
		}
	}
	if params.Datetime != nil {
		search.Datetime = string(*params.Datetime)
	}
	if params.Q != nil {
		search.Q = []string(*params.Q)
	}
	if params.Type != nil {
		search.Types = []string(*params.Type)
	}
	if params.Ids != nil {
		search.IDs = []string(*params.Ids)
	}
	if params.ExternalIds != nil {
		search.ExternalIDs = []string(*params.ExternalIds)
	}
	if params.Limit != nil {
		search.Limit = int(*params.Limit)
	}
	if search.Limit < 0 || search.Limit > s.maximumLimit {
		return search, "", fmt.Errorf("limit must be between 0 and %d", s.maximumLimit)
	}
	var err error
	search.Sort, err = parseSort(params.Sortby)
	if err != nil {
		return search, "", err
	}
	search.Sort, err = catalog.NormalizeSort(search.Sort, catalogValue.Bundle.DefaultSortOrder, catalogValue.Bundle.Sortables)
	if err != nil {
		return search, "", err
	}
	if params.Filter != nil {
		search.Filter = string(*params.Filter)
	}
	if params.FilterLang != nil && string(*params.FilterLang) != "cql2-text" {
		return search, "", fmt.Errorf("filter-lang must be cql2-text")
	}
	if params.FacetsParameter != nil {
		value := string(*params.FacetsParameter)
		search.Facets = &value
	}
	scope, err := cursor.Scope(search)
	if err != nil {
		return search, "", err
	}
	if params.Cursor != nil {
		search.Position, err = s.cursors.Decode(string(*params.Cursor), catalogValue.ID, scope, search.Sort)
		if err != nil {
			return search, "", err
		}
	}
	return search, scope, nil
}

func (s *Service) catalogSearch(params api.GetCollectionsParams) (store.Search, string, error) {
	search := store.Search{Limit: s.defaultLimit}
	if params.Bbox != nil {
		for _, v := range *params.Bbox {
			search.Bbox = append(search.Bbox, float64(v))
		}
	}
	if params.Datetime != nil {
		search.Datetime = string(*params.Datetime)
	}
	if params.Q != nil {
		search.Q = []string(*params.Q)
	}
	if params.Type != nil {
		search.Types = []string(*params.Type)
	}
	if params.Ids != nil {
		search.IDs = []string(*params.Ids)
	}
	if params.ExternalIds != nil {
		search.ExternalIDs = []string(*params.ExternalIds)
	}
	if params.Limit != nil {
		search.Limit = int(*params.Limit)
	}
	if search.Limit < 0 || search.Limit > s.maximumLimit {
		return search, "", fmt.Errorf("limit must be between 0 and %d", s.maximumLimit)
	}
	var err error
	search.Sort, err = parseSort(params.Sortby)
	if err != nil {
		return search, "", err
	}
	allowed := map[string]store.Sortable{"id": {Type: "string", Path: "/id"}, "type": {Type: "string", Path: "/type"}, "title": {Type: "string", Path: "/title"}, "description": {Type: "string", Path: "/description"}, "created": {Type: "string", Format: "date-time", Path: "/properties/created"}, "updated": {Type: "string", Format: "date-time", Path: "/properties/updated"}}
	search.Sort, err = catalog.NormalizeSort(search.Sort, []store.SortField{{Property: "id", Direction: "asc"}}, allowed)
	if err != nil {
		return search, "", err
	}
	if params.Filter != nil {
		search.Filter = string(*params.Filter)
	}
	if params.FilterLang != nil && string(*params.FilterLang) != "cql2-text" {
		return search, "", fmt.Errorf("filter-lang must be cql2-text")
	}
	scope, err := cursor.Scope(search)
	if err != nil {
		return search, "", err
	}
	if params.Cursor != nil {
		search.Position, err = s.cursors.Decode(string(*params.Cursor), "$catalogs", scope, search.Sort)
		if err != nil {
			return search, "", err
		}
	}
	return search, scope, nil
}

func (s *Service) links(ctxURL *url.URL, scope, catalogID string, search store.Search, first, last []any, hasPrev, hasNext bool, mediaType string) []api.Link {
	links := []api.Link{makeLink(s.publicURL, ctxURL, "self", "", mediaType)}
	if hasNext && len(last) > 0 {
		if token, err := s.cursors.Encode(catalogID, scope, search.Sort, store.CursorNext, last); err == nil {
			links = append(links, makeLink(s.publicURL, ctxURL, "next", token, mediaType))
		}
	}
	if hasPrev && len(first) > 0 {
		if token, err := s.cursors.Encode(catalogID, scope, search.Sort, store.CursorPrev, first); err == nil {
			links = append(links, makeLink(s.publicURL, ctxURL, "prev", token, mediaType))
		}
	}
	return links
}
func makeLink(publicURL string, current *url.URL, rel, token, mediaType string) api.Link {
	copy := *current
	query := copy.Query()
	if token != "" {
		query.Set("cursor", token)
	}
	copy.RawQuery = query.Encode()
	href := strings.TrimRight(publicURL, "/") + copy.EscapedPath()
	if copy.RawQuery != "" {
		href += "?" + copy.RawQuery
	}
	return api.Link{Href: href, Rel: rel, Type: &mediaType}
}
func expectedVersion(value *string) (*int64, error) {
	if value == nil {
		return nil, nil
	}
	if strings.TrimSpace(*value) == "*" {
		wildcard := int64(-1)
		return &wildcard, nil
	}
	version, err := etag.Parse(*value)
	if err != nil {
		return nil, err
	}
	return &version, nil
}
func location(publicURL, catalogID, recordID string) string {
	return strings.TrimRight(publicURL, "/") + "/collections/" + url.PathEscape(catalogID) + "/items/" + url.PathEscape(recordID)
}

func schemaProperties[T any](input map[string]T, facetDefinitions map[string]store.FacetDefinition) map[string]any {
	result := map[string]any{}
	faceted := map[string]bool{}
	for _, definition := range facetDefinitions {
		if definition.Property != "" {
			faceted[definition.Property] = true
		}
	}
	names := make([]string, 0, len(input))
	for name := range input {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		raw, _ := json.Marshal(input[name])
		var value map[string]any
		_ = json.Unmarshal(raw, &value)
		delete(value, "x-tlon-path")
		if faceted[name] {
			value["facet"] = true
		}
		result[name] = value
	}
	return result
}
